FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04

# 필수 패키지 설치 + PortAudio
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    git \
    build-essential \
    libportaudio2 \
    portaudio19-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip3 install --upgrade pip

# PyTorch는 따로 설치
RUN pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

# 나머지 requirements 설치
RUN pip3 install -r requirements.txt

CMD ["bash"]


# docker run --rm -it --gpus all ^
#   -v "%cd%":/app ^
#   -w /app ^
#   --name noise_dev_gpu ^
#   noise-pytorch-gpu
